name: Run Tests

on: [pull_request,workflow_dispatch]

permissions:
  contents: read

jobs:
  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install Formatting
      run: |
        pip install autopep8 flake8 flake8-no-implicit-concat
    - name: Check Formatting
      run: |
        flake8 tests
        flake8 trimesh
        echo ${{github.ref}}
        flake8 examples
        flake8 setup.py
        autopep8 --recursive --aggressive --diff --exit-code trimesh/
        autopep8 --recursive --aggressive --diff --exit-code examples/
        autopep8 --recursive --aggressive --diff --exit-code tests/

  tests:
    name: Run Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            python-version: 2.7
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test a minimal install
      run: |
        pip install .
        python tests/test_minimal.py
    - name: Install Trimesh
      run: pip install .[easy,test]
    - name: Run Pytest
      run: pytest
  docker:
    name: Run Tests In Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Pytest In Docker
      run: make test
